package io.getstream.chat.java.models;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonProperty;

public enum Language {
  @JsonProperty("af")
  AF,
  @JsonProperty("am")
  AM,
  @JsonProperty("ar")
  AR,
  @JsonProperty("az")
  AZ,
  @JsonProperty("bg")
  BG,
  @JsonProperty("bn")
  BN,
  @JsonProperty("bs")
  BS,
  @JsonProperty("cs")
  CS,
  @JsonProperty("da")
  DA,
  @JsonProperty("de")
  DE,
  @JsonProperty("el")
  EL,
  @JsonProperty("en")
  EN,
  @JsonProperty("es")
  ES,
  @JsonProperty("es-MX")
  ES_MX,
  @JsonProperty("et")
  ET,
  @JsonProperty("fa")
  FA,
  @JsonProperty("fa-AF")
  FA_AF,
  @JsonProperty("fi")
  FI,
  @JsonProperty("fr")
  FR,
  @JsonProperty("fr-CA")
  FR_CA,
  @JsonProperty("ha")
  HA,
  @JsonProperty("he")
  HE,
  @JsonProperty("hi")
  HI,
  @JsonProperty("hr")
  HR,
  @JsonProperty("hu")
  HU,
  @JsonProperty("id")
  ID,
  @JsonProperty("it")
  IT,
  @JsonProperty("ja")
  JA,
  @JsonProperty("ka")
  KA,
  @JsonProperty("ko")
  KO,
  @JsonProperty("lv")
  LV,
  @JsonProperty("ms")
  MS,
  @JsonProperty("nl")
  NL,
  @JsonProperty("no")
  NO,
  @JsonProperty("pl")
  PL,
  @JsonProperty("ps")
  PS,
  @JsonProperty("pt")
  PT,
  @JsonProperty("ro")
  RO,
  @JsonProperty("ru")
  RU,
  @JsonProperty("sk")
  SK,
  @JsonProperty("sl")
  SL,
  @JsonProperty("so")
  SO,
  @JsonProperty("sq")
  SQ,
  @JsonProperty("sr")
  SR,
  @JsonProperty("sv")
  SV,
  @JsonProperty("sw")
  SW,
  @JsonProperty("ta")
  TA,
  @JsonProperty("th")
  TH,
  @JsonProperty("tl")
  TL,
  @JsonProperty("tr")
  TR,
  @JsonProperty("uk")
  UK,
  @JsonProperty("ur")
  UR,
  @JsonProperty("vi")
  VI,
  @JsonProperty("zh")
  ZH,
  @JsonProperty("zh-TW")
  ZH_TW,
  @JsonEnumDefaultValue
  UNKNOWN
}
