name: javadoc
on:
  push:
    branches:
      - main
jobs:
  javadoc:
    runs-on: ubuntu-latest
    concurrency: docs-${{ github.ref }}
    name: 📚 Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Generate doc
        run: ./gradlew --no-daemon javadoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs/javadoc/
