name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish to MavenCentral
        run: ./gradlew test --no-daemon
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          STREAM_SECRET: ${{ secrets.STREAM_SECRET }}
